export const ADD_PRODUCT_START = "ADD_PRODUCT_START";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";

export const GET_PRODUCT_LIST_START = "GET_PRODUCT_LIST_START";
export const GET_PRODUCT_LIST_FAIL = "GET_PRODUCT_LIST_FAIL";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";

export const VIEW_PRODUCT_START = "VIEW_PRODUCT_START";
export const VIEW_PRODUCT_FAIL = "VIEW_PRODUCT_FAIL";
export const VIEW_PRODUCT_SUCCESS = "VIEW_PRODUCT_SUCCESS";

export const DELETE_PRODUCT_START = "DELETE_PRODUCT_START";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";

export const EDIT_PRODUCT_START = "EDIT_PRODUCT_START";
export const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
