export const ADD_USER_START = "ADD_USER_START";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";

export const GET_USER_LIST_START = "GET_USER_LIST_START";
export const GET_USER_LIST_FAIL = "GET_USER_LIST_FAIL";
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";

export const VIEW_USER_START = "VIEW_USER_START";
export const VIEW_USER_FAIL = "VIEW_USER_FAIL";
export const VIEW_USER_SUCCESS = "VIEW_USER_SUCCESS";

export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

export const EDIT_USER_START = "EDIT_USER_START";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";

export const SELECTED_USER = "SELECTED_USER";
