export const ADD_ROLE_START = "ADD_ROLE_START";
export const ADD_ROLE_FAIL = "ADD_ROLE_FAIL";
export const ADD_ROLE_SUCCESS = "ADD_ROLE_SUCCESS";

export const GET_ROLE_LIST_START = "GET_ROLE_LIST_START";
export const GET_ROLE_LIST_FAIL = "GET_ROLE_LIST_FAIL";
export const GET_ROLE_LIST_SUCCESS = "GET_ROLE_LIST_SUCCESS";

export const VIEW_ROLE_START = "VIEW_ROLE_START";
export const VIEW_ROLE_FAIL = "VIEW_ROLE_FAIL";
export const VIEW_ROLE_SUCCESS = "VIEW_ROLE_SUCCESS";

export const DELETE_ROLE_START = "DELETE_ROLE_START";
export const DELETE_ROLE_FAIL = "DELETE_ROLE_FAIL";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";

export const EDIT_ROLE_START = "EDIT_ROLE_START";
export const EDIT_ROLE_FAIL = "EDIT_ROLE_FAIL";
export const EDIT_ROLE_SUCCESS = "EDIT_ROLE_SUCCESS";
